apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  externalTrafficPolicy: Local #https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/instance-navigation-often-fails-with-crumb-issuer-errors
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer