apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-cloning
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: nginx-claim